### ISSUE TITLE
Alpine runner

### ISSUE THREAD

**Issue by Syntax3rror404** [myoung34/docker-github-actions-runner#163]
Hi, thank you for your runner image. It have over 1 GB. Can you also build a alpine image?

**Comment by myoung34** [comment]
Im open to PR's, but alpine is the same size as ubuntu (within 22mb - ubuntu is 25mb alpine is ~3); its the extra packages that add that size

Also my runners are generally 400-550mb, not over 1GB

**Comment by samsen1** [comment]
Unless I'm doing something wrong, my runner ends up over 1GB. Your base alone is close to 1GB.

```
docker images | grep myoung
myoung34/github-runner                                                    latest                               bbc47362c2c3   18 hours ago   1.48GB
myoung34/github-runner-base                                               latest                               e23727f9f6c2   4 weeks ago    1.06GB

```

**Comment by Syntax3rror404** [comment]
I have this problem too. The gitlab runner have only 50mb. 1 GB  or 500 MB are much to big for a container image.

**Comment by Syntax3rror404** [comment]
The problem is he download all the stuff for compiling packages. You can use a building container and then copy the binarys to the container image so you dont have the useless binarys that are not used for execute all the stuff 

for example: https://github.com/Syntax3rror404/ansible-runner/blob/master/Dockerfile

@myoung34 
you could have a look at that. That would improve the quality of your code considerably as well as the security.

**Comment by samsen1** [comment]
Other than the curl and make install for git, i dont see anywhere you could save storage on. Everything else is a simple `apt install`. As a test, i removed the installation of `git` and that shaved off 100mb. The thinking here was installing git from package instead of compiling from scratch, but i understand why that was needed.

**Comment by Syntax3rror404** [comment]
we dont need make for example, only for the AS builder container

**Comment by samsen1** [comment]
I went a bit further, looks like the docker-in-docker stuff adds a little over 500Mb. I for one need this container because I need a runner that can build docker images.

**Comment by myoung34** [comment]
I think theres some confusion

Yes, the base is well over 1GB, but that image is purely for speed and resiliency. Using this project does not use the base image.

The main images published pull from the base, add the actual last steps of github runner stuff then do a ton of cleanup. The final artifacts for others to use are not 1GB (as far as pulling/pushing goes)

![](https://i.imgur.com/bSUKCSG.png)

The process would be the same for alpine, I honestly doubt the final products are going to be much smaller after all the compilation/dependencies are gone

That said, I'm not against alpine and open to pull requests but I personally will not make that change because alpine does not have a security mailing list, the versioning is hard to capture semantically and runners are basically stateless so theres little benefit (biased from me) from that effort. If someone wants it im happy to help

If the issue is size we can also investigate whats causing bloat and work on slimming up the final layers. There are good projects for this like [dive](https://github.com/wagoodman/dive)

Just using `FROM x AS y` in docker does not improve security, as security is not the driving force for using alpine. If theres a benefit to adding alpine, go for it. But if size is an issue I recommend first seeing if you can find ways to slim down this one.

**Comment by myoung34** [comment]
There's multiple efforts it seems in this issue.

> That would improve the quality of your code considerably as well as the security.

> It have over 1 GB.

> Can you also build a alpine image?

Are you concerned with size, os, or security?
This is sounding like an XY problem where if the issue is size then just swapping the entire OS out vs optimizing the one in play is kind of obfuscated. 

Whats the actual concern here?

**Comment by samsen1** [comment]
We can all sit here and nitpick but I'm not going to do that. I love what you've done here and will continue to use this image. My only concern was the size of the image. I'm definitely seeing over 1GB (see my earlier comment w/ output) when I pull down the image. As a test, I started to remove some of the "extra" stuff like installing git and docker from the end of the Dockerfile and it makes a HUGE difference.

The original request was for alpine, I dont have a preference; I just happened to come across this ticket because I was wondering about the size of the final container.

**Comment by myoung34** [comment]
If you can find workarounds that lower the image Im totally on board

[git just has to be a certain version](https://github.com/myoung34/docker-github-actions-runner/issues/125#issuecomment-892131734) but at the time when i made this that version wasnt available in apt. if its now available adn we can remove some build tools thats probably a win overall

Im not trying to nitpick on my side, Just trying to get to the bottom of the ask. Any optimizations are appreciated
