### ISSUE TITLE
Runner does not start anymore

### ISSUE THREAD

**Issue by vmk-dev** [myoung34/docker-github-actions-runner#219]
When starting the runner with the latest image tag I get this error:

```
Runner reusage is disabled
Obtaining the token of the runner
curl: (6) getaddrinfo() thread failed to start
Disable auto update option is enabled
Configuring
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
```

Any ideas?

**Comment by myoung34** [comment]
This is a dupe of #216
Im going to roll back `latest` to `focal` due to the widespread nature of jammy

**Comment by myoung34** [comment]
Testing with https://github.com/myoung34/docker-github-actions-runner/commit/4064635fcd8764208492a04475315e2adb4d43f5

cc @Ru13en for a #211 regression. Jammy will be available as a named tag but not `latest`

**Comment by vmk-dev** [comment]
@myoung34 thank you for the quick response. Just pulled the latest tag of your rolled back image and now it works like a charm again!

**Comment by Ru13en** [comment]
@vmk-dev running older versions of the Docker engine are not compatible with jammy-based containers.
This issue is caused because you don't have the latest docker version.
Please try to upgrade the docker to at least version 20.10.10 or add --security-opt seccomp=unconfined to the runner.
@myoung34 maybe you could add this info to README...
