### ISSUE TITLE
awscli?

### ISSUE THREAD

**Issue by rs-garrick** [myoung34/docker-github-actions-runner#23]
Can I request that awscli be installed inside the container?  It would be huge convienence.

**Comment by rs-garrick** [comment]
Note that github-hosted runners have awscli installed.

**Comment by myoung34** [comment]
The only reason Ive avoided this is because AWSCLI v2 is out but not fully set up as a drop in replacement across most places, so versioning it would be a bit hard.

you can however do this with pip or apt in the github workflow. tedious but until awscli v2 is the standard i hesitate to make that bias here

**Comment by rs-garrick** [comment]
Just put in whatever the github-hosted runner has?  Noone can complain if you are matching the head office.

**Comment by myoung34** [comment]
Fair. I added it to the base [here](https://github.com/myoung34/docker-github-actions-runner/commit/5aa8bddee3c0108f30f0ed859b41eb67b463c645)

unfortunately the base takes a stupid amount of time to build (hence why its separated), but itll make its way into `latest` _eventually_

**Comment by rs-garrick** [comment]
Thank you!

**Comment by myoung34** [comment]
```bash
$ docker run -it --entrypoint /bin/bash myoung34/github-runner
root@264c572dd66b:/actions-runner# aws --version
aws-cli/1.16.218 Python/3.7.5 Linux/4.19.76-linuxkit botocore/1.12.208
```

its up
