### ISSUE TITLE
Allow the runner to be removed gracefully

### ISSUE THREAD

**Issue by iagomls** [myoung34/docker-github-actions-runner#24]
[When using Kubernetes](https://github.com/myoung34/docker-github-actions-runner#kubernetes), it's possible to run a command when the container is stopped. If the runner is not stopped propertly then the runner is not removed from GitHub interface.

Using Kubernetes, can be done by using a [lifecycle hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/). It would be great if we could suppport that. These are the requirements:

* The shell script to remove the runner should be available in the image.
* `RUNNER_TOKEN` must be available again, so we can call `./remove.sh` and pass the runner token. Looks like [it was removed recently](https://github.com/myoung34/docker-github-actions-runner/commit/3d44159889d799f770a4a1e66771ae90a08122da).
* The README must be updated containing the instructions to gracefully stop the runner.

**Comment by myoung34** [comment]
I dont have a k8s cluster currently to test with but if you can come up with a PR id be happy to review it

**Comment by myoung34** [comment]
I added some basic support for SIGTERM in https://github.com/myoung34/docker-github-actions-runner/commit/7648aa420578fa0840a0886c20973c9ada716fa6

this _should_ clean up as you expect but it assumes an access key

if youre using a time based token it wont work as expected since those can expire before it handles sigterm
