### ISSUE TITLE
armv7

### ISSUE THREAD

**Issue by loopingz** [myoung34/docker-github-actions-runner#246]
Hello,

I think in the past you use to build for armv7 and I noticed it is not the case anymore. Even if the page on Docker Hub: https://hub.docker.com/r/myoung34/github-runner still reference it.

Is there a reason why?
I wanted to connect my raspberry pi cluster to github action, so would need an armv7 version.

Regards

**Comment by myoung34** [comment]
Armhf is not supported anymore. Arm64 is however which covers many pi models

**Comment by myoung34** [comment]
Armhf is not supported anymore. Arm64 is however which covers many pi models.

I don't plan on supporting anything other than arm64 due to packaging issues and discrepancies in the Ubuntu/Debian package base unfortunately. 
Its worth noting that armv7 really only covers the rasp pi model 2 and older. Pi3 and higher are supported.

I'll update the docker page however
