### ISSUE TITLE
Pushes do not use latest base image

### ISSUE THREAD

**Issue by LordChunk** [myoung34/docker-github-actions-runner#296]
Builds from the ``deploy.yml`` don't workflow don't use the latest base image when you push a new commit. This is because the build steps in ``deploy.yml`` don't wait for ``base.yml`` to finish before starting. 

This issue doesn't occur on scheduled builds since there is a significant time between the start of the base image build and the main image build.

**Comment by myoung34** [comment]
That's only true if the pull request modifies the base docker file.  For any build it will use whatever the most recent push of base is, which thanks to nightly builds is no more than 24h old. Because thats just not often enough that; I've not considered a solution

If you've got any ideas for a pull request I'm happy to review
