### ISSUE TITLE
Runner not showing up in Github but no errors

### ISSUE THREAD

**Issue by doct0r** [myoung34/docker-github-actions-runner#334]
I am trying to register a runner using Bash; my command looks like this:
`github-runner % docker run -d --restart always --platform linux/amd64 --name github-runner-ios \
  -e ACCESS_TOKEN="my_PAT" \
  -e RUNNER_NAME="ios-runner" \
  -e RUNNER_WORKDIR="/tmp/github-runner-ios" \
  -e RUNNER_SCOPE="repo" \
  -e REPO_URL="repo_URL" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/github-runner-ios:/tmp/github-runner-ios \
  myoung34/github-runner:latest`

When I run it I don't get any errors but the runner doesn't appear at my repo. I've used the exact same command for another repo and it works, so I'm not sure where it goes wrong. The only difference I can think of is that this repo is part of an organization while the other is my personal repo. Do I have to use ORG level access in this case?

**Comment by myoung34** [comment]
This is likely a setting on the organization itself and not due to the runner at all. I would assume you do need org permissions to be a runner in an org with additional permissions

**Comment by timnolte** [comment]
@doct0r I was just running into this today when I was setting up the runner as an organization runner instead of a repository runner. If you happen to be not seeing this on a public repo you have to explicitly turn this on for public repos in the Default runner group, or whatever group you have setup your runners in.

![image](https://github.com/myoung34/docker-github-actions-runner/assets/4312062/7ace4cea-0a5c-49e7-9edb-f9dec2898a03)

**Comment by myoung34** [comment]
Closing from inactivity
