### ISSUE TITLE
Can't use container syntax

### ISSUE THREAD

**Issue by tabossert** [myoung34/docker-github-actions-runner#42]
Do you know if it's possible to get around this error currently

"Container feature is not supported when runner is already running inside container."

Thanks

**Comment by myoung34** [comment]
How are you seeing this? Without reproducing it, I'm not sure

**Comment by tabossert** [comment]
Running a workflow that contains this in workflow

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer

ends up with 

<img width="1012" alt="Screen Shot 2020-07-16 at 4 01 20 PM" src="https://user-images.githubusercontent.com/37596773/87730783-9dc51600-c77d-11ea-8882-5b03d600acb5.png">

**Comment by myoung34** [comment]
Have you tried this? https://github.com/actions/runner/pull/383

Otherwise im not sure you can do it without opening up a ticket on actions/runner according to: https://github.com/actions/runner/blob/f9b5d626c5486d1f02b3bd45879f61834b7aeecc/src/Runner.Worker/ContainerOperationProvider.cs#L68

If there's no option to disable it, then it wont work as long as `/proc/1/cgroup` contains `:/docker/` according to that code

**Comment by tabossert** [comment]
I had not, thanks for sharing, I will try it and let you know

**Comment by myoung34** [comment]
Ill close for now, if you come up with anything re-open and we'll circle back
