### ISSUE TITLE
Alpine Variant

### ISSUE THREAD

**Issue by ScottPierce** [myoung34/docker-github-actions-runner#60]
Would it be possible to create an alpine variant of this?

**Comment by myoung34** [comment]
It's not out of the question but I only wrote Ubuntu since that's what the upstream is.

Imo with Ubuntu slim and cross arch it's not really worth the hassle given that alpine doesn't have a security mailing list and musl has strange issues.

That said if someone submitted a working pr I wouldn't be against it but it's not something that I would personally put my effort into
